name: Auto-Assign

on:
  issues:
    types:
      - opened

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue
        uses: actions-ecosystem/action-assign@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ayden-g
